---
name: "Changebot Deployment Notifier"
description: "Notify Changebot of deployments"
author: "Changebot"
branding:
  icon: "rocket"
  color: "green"
inputs:
  environment:
    description: "Deployment environment"
    required: false
    default: "production"
  endpoint:
    description: "API endpoint URL (for testing only)"
    required: false
    default: "https://api.changebot.ai/v1/deployments"
runs:
  using: "composite"
  steps:
    - name: Get OIDC Token
      id: oidc
      uses: actions/github-script@v7
      with:
        script: |
          const token = await core.getIDToken('changebot.ai');
          core.setSecret(token);
          core.setOutput('token', token);

    - name: Notify Changebot
      shell: bash
      run: |
        URL="${{ inputs.endpoint }}"
        PAYLOAD=$(jq -n \
          --arg sha "${{ github.sha }}" \
          --arg env "${{ inputs.environment }}" \
          --arg repo_id "${{ github.repository_id }}" \
          '{sha: $sha, environment: $env, repository_id: $repo_id}')

        attempt=1
        while [ $attempt -le 3 ]; do
          if curl -f --max-time 30 \
            -X POST \
            -H "Authorization: Bearer ${{ steps.oidc.outputs.token }}" \
            -H "Content-Type: application/json" \
            --data "$PAYLOAD" \
            "$URL"; then
            echo "✅ Deployment notification sent successfully"
            exit 0
          fi
          [ $attempt -lt 3 ] && sleep $((attempt * 2 + RANDOM % 3))
          ((attempt++))
        done

        echo "❌ Failed to send deployment notification after 3 attempts"
        exit 1
